name: Upload Analysis Zip as Artifact

on:
  workflow_dispatch:

jobs:
  upload_artifact:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create analysis.zip
        run: |
          Compress-Archive -Path C:\FusionLiteProjects\OrchardCore\Data\Imports\* -DestinationPath C:\FusionLiteProjects\OrchardCore\Data\Imports\analysis.zip -Force

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: analysis-zip
          path: C:\FusionLiteProjects\OrchardCore\Data\Imports\analysis.zip
