# This is a basic workflow to help you get started with Actions

name: Set-up And Build Orchard Core

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Clone Latest Orchardcore
        run: |
          cd D:\Applications
          if (Test-Path -Path "D:\Applications\OrchardCore") {
            Remove-Item -Path "D:\Applications\OrchardCore" -Recurse -Force
          }
          #git clone https://github.com/OrchardCMS/OrchardCore.git
          Invoke-WebRequest -Uri https://codeload.github.com/OrchardCMS/OrchardCore/zip/refs/tags/v1.8.3 -OutFile OrchardCore.zip
          Expand-Archive -Path OrchardCore.zip -DestinationPath . -Force
          Rename-Item -Path .\OrchardCore-1.8.3 -NewName OrchardCore -Force
          
          cd .\OrchardCore\
          Copy-Item -Path "${{ github.workspace }}\Remote\*" -Destination . -Recurse -Force
          
      # Runs a set of commands using the runners shell
      - name: Build The Project
        run: |
          cd D:\Applications\OrchardCore\src\OrchardCore.Cms.Web
          dotnet build --framework net8.0
