# This is a basic workflow to help you get started with Actions

name: Instrument OrchardCore

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Clone Latest Config Files into Local & Remote
        run: |
          cd C:\FusionLiteProjects\OrchardCore\
          Copy-Item -Path "${{ github.workspace }}\Local\*" -Destination . -Recurse -Force

          cd D:\Applications\OrchardCore\
          Copy-Item -Path "${{ github.workspace }}\Remote\*" -Destination . -Recurse -Force
          Copy-Item -Path ".\FusionLiteProject.properties" -Destination ".\src\OrchardCore.Cms.Web\bin\Debug\net8.0\" -Recurse -Force
          
      # Runs a set of commands using the runners shell
      - name: Instrument The Project
        run: |
          cd D:\Applications\OrchardCore\
          .\Project.ps1 project

      - name: Decompile The Project
        run: |
          cd D:\Applications\OrchardCore\
          .\Project.ps1 decompile
