# This is a basic workflow to help you get started with Actions

name: Run OrchardCore

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      operation:
        description: 'Run Original or Instrumented?'
        required: true
        type: choice
        options:
          - original
          - instrumented

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Executing ${{ github.event.inputs.operation }}
        run: |
          cd D:\Applications\OrchardCore\src\OrchardCore.Cms.Web
          .\Run.ps1 ${{ github.event.inputs.operation }}
      
